### ISSUE TITLE
Avoid using stuff from dependencies of dependencies

### ISSUE THREAD

**Issue by M4eqP** [cf-control/cf-control#52]
A lot of classes use calls to dependencies of dependencies. This is very bad style, as this might break easily when upgrading the direct dependencies.

What I spotted so far is the use of some preconditions class from `com.google.guava`. In https://github.com/cf-control/cf-control/tree/features/diff-functionality, I already implemented a custom preconditions class offering the `null` check. We should consider extracting the change from there and merging it in a separate PR, and replace all the existing precondition checks, too.

CC @cmatgh @felix-oq @yenle2501

**Comment by cmatgh** [comment]
Google Guava is a utility library that makes the handling of all kind of things easier. Preconditions is one of it's useful classes. It's not an internal class, it's part of the API.
For more info: (https://github.com/google/guava/wiki/PreconditionsExplained)
Having said that, i think we should stick to the google preconditions class, instead of writing our own, since it provides other useful precondition ckecks also.

**Comment by M4eqP** [comment]
Nevermind then. I just re-checked the gradle file, it's in fact already declared as a direct dependency. Let's just use that then.

Have you added it to the BOM?
